k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: dev
  currentCluster: arn:aws:eks:eu-west-1:510752977537:cluster/tf-dev-01
  clusters:
    arn:aws:eks:ca-central-1:226817515299:cluster/tf-prod-ca-01:
      namespace:
        active: production
        favorites:
        - production
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:226817515299:cluster/tf-prod-eu-01:
      namespace:
        active: production
        favorites:
        - production
        - default
      view:
        active: secret
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:510752977537:cluster/tf-dev-01:
      namespace:
        active: development
        favorites:
        - development
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:510752977537:cluster/tf-dev-02:
      namespace:
        active: development
        favorites:
        - development
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:609445407176:cluster/tf-pre-prod-01:
      namespace:
        active: pre-prod
        favorites:
        - pre-prod
        - default
      view:
        active: job
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:609445407176:cluster/tf-pre-prod-02:
      namespace:
        active: default
        favorites:
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:us-east-1:226817515299:cluster/tf-prod-us-01:
      namespace:
        active: production
        favorites:
        - production
        - all
        - default
      view:
        active: cronjob
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
